# Generated by Django 5.1.5 on 2025-07-13 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "management_system",
            "0002_alter_evaluation_options_alter_meeting_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал встречу",
            ),
            preserve_default=False,
        ),
    ]
